version: "3.8"

services:
  healing_project:
    container_name: healing_project
    build: 
      context: .
      dockerfile: Dokerfile
    stdin_open: True
    tty: True
    restart: always
    ports:
      - "8001:8001"
    volumes:
      - .:/app
    command: ["/bin/bash", "-c", "python manage.py runserver 0.0.0.0:8001"]
